name: update

permissions:
  contents: write

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MPV_EASY_CDN_UPDATER_TOKEN: ${{ secrets.MPV_EASY_CDN_UPDATER_TOKEN }}
  USERNAME: ahaoboy
  REPO_DESCRIPTION: "Created via MPV_EASY_CDN_UPDATER_TOKEN"
  REPO_NAME: "mpv-easy-cdn"

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: install
        run: |
          pnpm i

      - name: delete mpv-easy-cdn
        run: |
          curl -s -X DELETE  -H "Authorization: token $MPV_EASY_CDN_UPDATER_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$USERNAME/$REPO_NAME"

      - name: ls
        run: |
          ls -l

      - name: update base
        run: |
          pnpm run update-base
          ls -l

      - name: update-zip
        run: |
          pnpm run update-zip
          ls -l

      - name: ls
        run: |
          ls -l
      - name: create mpv-easy-cdn
        run :  |
          curl -s -X POST -H "Authorization: token $MPV_EASY_CDN_UPDATER_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/repos -d "{\"name\":\"$REPO_NAME\",\"description\":\"$REPO_DESCRIPTION\",\"private\":false}"

      - name: push
        run: |
          rm -rf ./.git
          git config --global init.defaultBranch main
          git init
          git config user.name "MPV_EASY_CDN_UPDATER"
          git config user.email "MPV_EASY_CDN_UPDATER@example.com"
          git remote add origin https://github.com/$USERNAME/$REPO_NAME.git
          git branch --set-upstream-to=origin/main main


          git add .
          git commit -am"update by ci"
          git gc --prune=now
          git push
