name: update

permissions:
  contents: write

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      branch:
        description: "branch"
        required: false
        type: string
        default: dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'dev' }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: clear
        run: |
          git fetch origin
          git checkout -b main origin/main
          
          ls -l
          git config --global init.defaultBranch main
          git config --global user.email "mpv-easy@mpv.com"
          git config --global user.name "mpv-easy-cdn"
          git config --global --type bool push.autoSetupRemote true

          git reset --hard dev
          # git checkout dev
          pnpm i

      - name: ls
        run: |
          ls -l

      - name: update base
        run: |
          pnpm run update-base
          ls -l

      - name: update-zip
        run: |
          pnpm run update-zip
          ls -l

      - name: commit
        run: |
          git add .
          git commit -am"update by ci"
          git gc --prune=now

      - name: ls
        run: |
          ls -l
      - name: push
        run: |
          git checkout --orphan temp_main
          git push origin temp_main:main --force
          git branch -D temp_main
          git push origin --all --force

      # - name: push
      #   uses: peaceiris/actions-gh-pages@v4
      #   if: github.ref == 'refs/heads/dev'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./
      #     publish_branch: main
      #     force_orphan: true
      #     cname: github.com
